# Mappa dei percorsi per i file mensili
db = [
    ["./dataset/201301/daily.txt", "./dataset/201301/hourly.txt", "./dataset/201301/monthly.txt", "./dataset/201301/precip.txt", "./dataset/201301/remarks.txt", "./dataset/201301/station.txt"],
    ["./dataset/201302/daily.txt", "./dataset/201302/hourly.txt", "./dataset/201302/monthly.txt", "./dataset/201302/precip.txt", "./dataset/201302/remarks.txt", "./dataset/201302/station.txt"],
    ["./dataset/201303/daily.txt", "./dataset/201303/hourly.txt", "./dataset/201303/monthly.txt", "./dataset/201303/precip.txt", "./dataset/201303/remarks.txt", "./dataset/201303/station.txt"],
    ["./dataset/201304/daily.txt", "./dataset/201304/hourly.txt", "./dataset/201304/monthly.txt", "./dataset/201304/precip.txt", "./dataset/201304/remarks.txt", "./dataset/201304/station.txt"],
    ["./dataset/201305/daily.txt", "./dataset/201305/hourly.txt", "./dataset/201305/monthly.txt", "./dataset/201305/precip.txt", "./dataset/201305/remarks.txt", "./dataset/201305/station.txt"],
    ["./dataset/201306/daily.txt", "./dataset/201306/hourly.txt", "./dataset/201306/monthly.txt", "./dataset/201306/precip.txt", "./dataset/201306/remarks.txt", "./dataset/201306/station.txt"],
    ["./dataset/201307/daily.txt", "./dataset/201307/hourly.txt", "./dataset/201307/monthly.txt", "./dataset/201307/precip.txt", "./dataset/201307/remarks.txt", "./dataset/201307/station.txt"],
    ["./dataset/201308/daily.txt", "./dataset/201308/hourly.txt", "./dataset/201308/monthly.txt", "./dataset/201308/precip.txt", "./dataset/201308/remarks.txt", "./dataset/201308/station.txt"],
    ["./dataset/201309/daily.txt", "./dataset/201309/hourly.txt", "./dataset/201309/monthly.txt", "./dataset/201309/precip.txt", "./dataset/201309/remarks.txt", "./dataset/201309/station.txt"],
    ["./dataset/201310/daily.txt", "./dataset/201310/hourly.txt", "./dataset/201310/monthly.txt", "./dataset/201310/precip.txt", "./dataset/201310/remarks.txt", "./dataset/201310/station.txt"],
    ["./dataset/201311/daily.txt", "./dataset/201311/hourly.txt", "./dataset/201311/monthly.txt", "./dataset/201311/precip.txt", "./dataset/201311/remarks.txt", "./dataset/201311/station.txt"],
    ["./dataset/201312/daily.txt", "./dataset/201312/hourly.txt", "./dataset/201312/monthly.txt", "./dataset/201312/precip.txt", "./dataset/201312/remarks.txt", "./dataset/201312/station.txt"],
]

states = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

typesD = {
    "1": "Daily",
    "2": "Hourly", 
    "3": "Monthly"
}

#daily
whD = {
    "Tmax": ("Maximum Temperature", "°F"), 
    "Tmin": ("Minimum Temperature", "°F"), 
    "Tavg": ("Average Temperature", "°F"),
    "Depart": ("Temperature Departure", "°F"),
    "DewPoint": ("Dew Point Temperature", "°F"),
    "WetBulb": ("Wet Bulb Temperature", "°F"),
    "Heat": ("Heating Degree Days", "°F-days"),
    "Cool": ("Cooling Degree Days", "°F-days"),
    "Depth": ("Snow Depth", "inches"),
    "Water1": ("Water Equivalent", "inches"),
    "SnowFall": ("Snowfall", "inches"),
    "PrecipTotal": ("Total Precipitation", "inches"),
    "StnPressure": ("Station Pressure", "inches of mercury"),
    "SeaLevel": ("Sea Level Pressure", "inches of mercury"),
    "ResultSpeed": ("Resultant Wind Speed", "mph"),
    "ResultDir": ("Resultant Wind Direction", "degrees"),
    "AvgSpeed": ("Average Wind Speed", "mph"),
    "Max5Speed": ("Max 5-Minute Wind Speed", "mph"),
    "Max2Speed": ("Max 2-Minute Wind Speed", "mph")
}

#hourly
wh = {
    "DryBulbFarenheit": ("Dry Bulb Temperature in Fahrenheit", "°F"),
    "DryBulbCelsius": ("Dry Bulb Temperature in Celsius", "°C"),
    "WetBulbFarenheit": ("Wet Bulb Temperature in Fahrenheit", "°F"),
    "WetBulbCelsius": ("Wet Bulb Temperature in Celsius", "°C"),
    "DewPointFarenheit": ("Dew Point in Fahrenheit", "°F"),
    "DewPointCelsius": ("Dew Point in Celsius", "°C"),
    "RelativeHumidity": ("Relative Humidity", "%"),
    "WindSpeed": ("Wind Speed", "m/s"),
    "WindDirection": ("Wind Direction", "°"),
    "StationPressure": ("Station Atmospheric Pressure", "hPa"),
    "SeaLevelPressure": ("Sea Level Pressure", "hPa"),
    "HourlyPrecip": ("Hourly Precipitation", "mm"),
}

#monthly
weather_units = {
    "AvgMaxTemp": ("Average Maximum Temperature", "°F"),
    "DepartureMaxTemp": ("Maximum Temperature Departure", "°F"),
    "AvgMinTemp": ("Average Minimum Temperature", "°F"),
    "DepartureMinTemp": ("Minimum Temperature Departure", "°F"),
    "AvgTemp": ("Average Temperature", "°F"),
    "DeparturefromNormal": ("Departure from Normal Temperature", "°F"),
    "AvgDewPoint": ("Average Dew Point", "°F"),
    "AvgWetBulb": ("Average Wet Bulb Temperature", "°F"),
    "HDDSeasonToDate": ("Heating Degree Days to Date", "°F"),
    "CDDSeasonToDate": ("Cooling Degree Days to Date", "°F"),
    "HDDSeasonToDateDeparture": ("Heating Degree Days Seasonal Departure", "°F"),
    "CDDSeasonToDateDeparture": ("Cooling Degree Days Seasonal Departure", "°F"),
    "MeanStationPressure": ("Mean Station Pressure", "hPa"),
    "MeanSeaLevelPressure": ("Mean Sea Level Pressure", "hPa"),
    "MaxSeaLevelPressure": ("Maximum Sea Level Pressure", "hPa"),
    "MinSeaLevelPressure": ("Minimum Sea Level Pressure", "hPa"),
    "TotalMonthlyPrecip": ("Total Monthly Precipitation", "inches"),
    "DepartureFromNormalPrecip": ("Precipitation Departure from Normal", "inches"),
    "Max24HrPrecip": ("Maximum 24-Hour Precipitation", "inches"),
    "TotalSnowfall": ("Total Snowfall", "inches"),
    "Max24HrSnowfall": ("Maximum 24-Hour Snowfall", "inches"),
    "Max12ZSnowDepth": ("Maximum 12Z Snow Depth", "inches"),
    "WaterEquivalent": ("Water Equivalent of Precipitation", "inches"),
    "ResultantWindSpeed": ("Resultant Wind Speed", "km/h"),
    "ResultantWindDirection": ("Resultant Wind Direction", "°"),
    "AvgWindSpeed": ("Average Wind Speed", "km/h"),
}


